# Generated by Django 6.0.7 on 2026-07-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_staff_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='account_holder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='bank_details_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='bank_details_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='coverage_month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('payshap', 'PayShap'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('debit_order', 'Debit Order')], max_length=20),
        ),
    ]
