# Generated by Django 6.0.7 on 2026-07-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_claim_account_holder_claim_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stitch_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
