# Generated by Django 6.0.7 on 2026-07-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_stitch_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stitch_payment_id',
            new_name='ozow_transaction_id',
        ),
    ]
