# Generated by Django 6.0.7 on 2026-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_stitch_payment_id_payment_ozow_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='fraud_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_risk_level',
            field=models.CharField(default='low', max_length=20),
        ),
    ]
